const QestionList = [[
        "데이터베이스 정규화와 비정규화의 차이점은 무엇인가요?",
        "트랜잭션이란 무엇이고, ACID는 어떤 원칙인가요?",
        "인증과 인가의 차이점은? JWT에 대해 설명해주세요.",
        "Redis를 사용하는 이유는 무엇인가요?",
        "REST API와 SOAP의 차이점을 설명해주세요.",
        "SQL과 NoSQL의 차이는 무엇인가요?",
        "ORM(Object-Relational Mapping)이란 무엇인가요?",
        "Docker와 같은 컨테이너 기술의 장점은 무엇인가요?",
        "CI/CD란 무엇이며, 어떻게 동작하나요?",
        "MVC 패턴이란 무엇인가요?",
        "웹 서버와 WAS(Web Application Server)의 차이는?",
        "GraphQL과 REST API의 차이점을 설명해주세요.",
        "JWT의 구조와 장단점은 무엇인가요?",
        "비동기 처리와 동기 처리의 차이점은?",
        "Node.js의 이벤트 루프(Event Loop)에 대해 설명해주세요.",
        "마이크로서비스 아키텍처(MSA)의 장점과 단점은?",
        "API 게이트웨이란 무엇이며 어떤 역할을 하나요?",
        "OAuth2.0 인증 흐름에 대해 설명해주세요.",
        "Load Balancer(로드 밸런서)의 역할은 무엇인가요?",
        "캐싱(Caching)이란 무엇이고, 언제 사용하는 것이 좋은가요?",
        "마이그레이션(Migration)이란 무엇이며, 어떻게 관리하나요?",
        "데이터베이스 인덱싱이란 무엇이고, 어떻게 활용하나요?",
        "SQL 조인(Join)의 종류와 각각의 차이점은?",
        "Deadlock(교착 상태)이란 무엇이며, 어떻게 해결하나요?",
        "Connection Pool이란 무엇이고, 왜 필요한가요?",
        "데이터 파티셔닝(Partitioning)이란 무엇인가요?",
        "Replication(복제)이란 무엇이고, 왜 사용하나요?",
        "CAP 정리란 무엇인가요?",
        "문제 발생 시 로그를 어떻게 설계하고 관리하나요?",
        "Health Check(헬스 체크)는 무엇이고, 어떻게 구현하나요?",
        "Rate Limiting(속도 제한)이란 무엇이고, 어떻게 구현하나요?",
        "CBR 회피 기법은 무엇인가요?",
        "Circuit Breaker 패턴이란 무엇인가요?",
        "Message Queue의 역할과 사용 예시는?",
        "RabbitMQ와 Kafka의 차이점은?",
        "Async Task(비동기 작업)를 어떻게 처리하나요?",
        "Webhook이란 무엇이고, 어떻게 활용하나요?",
        "Idempotency(멱등성)이란 무엇이고, 왜 중요한가요?",
        "서버 사이드 로깅 전략은 어떻게 구축하나요?",
        "Distributed Tracing이란 무엇인가요?",
        "gRPC란 무엇이며, 언제 사용하는 게 좋은가요?",
        "서버리스(Serverless)란 무엇이며, 장단점은?",
        "FaaS(Function as a Service)란 무엇인가요?",
        "CI 도구(Jenkins, GitHub Actions 등)의 역할은?",
        "GitOps란 무엇인가요?",
        "Infrastructure as Code(IaC)는 무엇이며, 도구는?",
        "Kubernetes란 무엇이고, 어떻게 작동하나요?",
        "컨테이너 오케스트레이션의 핵심 개념은?",
        "Secret Management(비밀 관리)을 어떻게 하나요?",
        "TLS/SSL 핸드쉐이크 과정을 설명해주세요.",
        "OWASP Top10은 무엇인가요?",
        "SQL Injection 공격은 무엇인가요? 방어 방법은?",
        "XSS(Cross-Site Scripting) 공격은 무엇인가요? 방어법은?",
        "CSRF(Cross-Site Request Forgery)란 무엇인가요?",
        "CORS(Cross-Origin Resource Sharing)란 무엇인가요?",
        "HTTPS란 무엇이며, HTTP와 다른 점은?",
        "VPN과 VPN 없이도 가능한 보안 방식은?",
        "API 버전 관리는 어떻게 설계하나요?",
        "Rate Limit, Throttling, Quota의 차이는 무엇인가요?",
        "스케일 업(Scale-up)과 스케일 아웃(Scale-out)의 차이는?",
        "서비스 무정지 배포(Zero Downtime Deployment) 방법은?",
        "Blue-Green 배포란 무엇인가요?",
        "Canary 배포란 무엇이고, 어떻게 구성하나요?",
        "롤백(Rollback)은 언제, 어떻게 처리하나요?",
        "로그와 메트릭, 트레이스의 관계를 설명해주세요.",
        "Prometheus와 Grafana의 역할은 무엇인가요?",
        "ELK/EFK 스택은 무엇이고, 언제 사용하는가요?",
        "HealthCheck와 ReadinessProbe, LivenessProbe 차이는?",
        "서킷 브레이커 구현 방법은?",
        "데이터 마이그레이션 전략은?",
        "데이터베이스 샤딩(Sharding)이란 무엇인가요?",
        "ACID vs BASE 철학의 차이는 무엇인가요?",
        "비동기 메시지와 동기 호출 선택 기준은?",
        "API 문서화 도구(Swagger/OpenAPI 등)는 어떤 역할을 하나요?",
        "Postman이나 Insomnia 같은 도구는 언제 사용하나요?",
        "IDP 기반 SSO(Single Sign-On)이란 무엇인가요?",
        "로그인 세션(Session)과 토큰(Token) 기반 인증의 차이는?",
        "OAuth vs JWT vs SAML의 차이점은?",
        "OAuth2.0의 Grant Type 종류는?",
        "API Throttling vs Rate Limit vs Quota 차이는?",
        "분산 시스템의 데이터 정합성 모델에 대해 설명해주세요.",
        "분산 락(Distributed Lock)이란 무엇인가요?",
        "2PC(Two-Phase Commit)란 무엇이고, 한계는?",
        "Saga 패턴이란 무엇인가요?",
        "CSV, JSON, Avro 등의 데이터 포맷 차이는?",
        "REST API에서 HATEOAS란 무엇인가요?",
        "웹훅(Webhook) vs 메시징 큐(MQ) 비교는?",
        "동시성 제어(Concurrency Control) 기법은?",
        "비동기 프로그래밍 모델(Promise, Future 등)의 차이는?",
        "백엔드 성능 튜닝 경험이 있다면?",
        "HTTP/2와 HTTP/1.1의 차이점은?",
        "gRPC와 REST API를 비교하면 어떤 장단점이 있나요?",
        "TLS 버전 차이와 최신 버전을 선택하는 이유는?",
        "프로토콜 버퍼(Protobuf)란 무엇인가요?",
        "성능 테스트(Load test, Stress test)를 어떻게 진행하나요?",
        "CI/CD 파이프라인에서 주요 단계는 무엇인가요?",
        "코드 리뷰(Code Review) 프로세스를 어떻게 운영하나요?",
        "에러 핸들링 전략은 어떻게 설계하나요?",
        "Fallback 메커니즘이란 무엇인가요?",
        "Elastic Scaling이란 무엇인가요?",
        "모니터링(Alerting) 시스템은 어떻게 구축하나요?",
        "Chaos Engineering이란 무엇인가요?",
        "API 라우팅과 리버스 프록시 구성은 어떻게 하나요?",
        "웹 서버(Nginx/Apache)와 리버스 프록시 차이는?",
        "TL;DR: 단일 책임 원칙(SRP)이란 무엇인가요?",
        "템플릿 엔진(EJS, Handlebars 등)이란 무엇인가요?",
        "서비스 메시(Service Mesh)란 무엇이고, 어떻게 동작하나요?",
        "CI/CD에서 Secret 관리는 어떻게 하나요?",
        "DDoS 공격이란 무엇이고, 어떻게 방어하나요?",
        "로그 포맷(JSON vs PlainText)의 장단점은?",
        "헬스 체크 API 설계 시 고려할 점은?",
        "Hot Reload vs Cold Restart의 차이는 무엇인가요?",
        "스타트업 환경에서 백엔드 개발의 주요 고려사항은?"
]];

export default QestionList;